---
title: "Plotting xts timeseries"
author: "Alejandro Ruete"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Plotting xts timeseries}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This vignette is adapted from https://rpubs.com/RLodge/timeseriesintro
## xts Objects
The ‘x’ in xts stands for extensible, named as such because it is an extension of zoo. An xts object is formed just as a zoo object is. However, an xts object is in matrix form and thus is easier to subset through.

What comes from the export function ...is an xts object.

library(xts)
mpls.temp.xts <- as.xts(mpls.zoo2)
head(mpls.temp.xts)
##                     [,1]
## 2017-01-01 00:53:00 27.0
## 2017-01-01 01:53:00 26.1
## 2017-01-01 02:53:00 26.1
## 2017-01-01 03:53:00 25.0
## 2017-01-01 04:53:00 24.1
## 2017-01-01 05:53:00 23.0
dim(mpls.temp.xts) #not NULL!
## [1] 1854    1
Sub-setting is convenient in xts as you can do it with its dates and with a / for a range of dates.

mpls.temp.xts["2017-01-01 00:53:00"] #temperature for new years
##                     [,1]
## 2017-01-01 00:53:00   27
mpls.temp.xts["2017-01-01 00:15:00/2017-01-01 03:15:00"] #first few hours of new years
##                     [,1]
## 2017-01-01 00:53:00 27.0
## 2017-01-01 01:53:00 26.1
## 2017-01-01 02:53:00 26.1
xts has several tools for converting to different periods. Here we will use to.hourly. This provides, the first, min, max, and last of the data.

mplstemp.h <- to.hourly(mpls.temp.xts) 
mplstemp.h["2017-01-03 08:53:00"]
##                     mpls.temp.xts.Open mpls.temp.xts.High
## 2017-01-03 08:53:00               15.1               15.1
##                     mpls.temp.xts.Low mpls.temp.xts.Close
## 2017-01-03 08:53:00                14                  14
Here’s the plot of the daily high temperatures. The plot command with an xts object provides a TON of features. This makes it fairly easy to customize your plots.

mplstemp.d <- to.daily(mpls.temp.xts)[,2]
plot(mplstemp.d, col = "darkblue", grid.ticks.on = "days", major.ticks = "days", grid.col = "lightgrey", main = "MPLS daily temp JAN-MAR 2017")
